// Seed configuration, written to the DB once (first boot with an empty
// AppraisalCriterion collection) and HR-editable from then on. Nothing
// below is read at scoring time — the engine only ever sees the DB copy.

const PAR = [
  { key: "poor", label: "Poor", pct: 33.33 },
  { key: "average", label: "Average", pct: 66.67 },
  { key: "excellent", label: "Excellent", pct: 100 },
];

export const DEFAULT_CRITERIA = [
  {
    key: "project_contribution",
    name: "Project Contribution",
    description: "Completion of assigned work weighted by each project's configured weightage — higher-weightage projects count more.",
    type: "automatic",
    group: "automatic",
    weightage: 15,
    metric: "project_weighted_completion",
    scoringMethod: "ratio",
    params: { noDataPct: 0 },
  },
  {
    key: "task_completion",
    name: "Task Completion",
    description: "Completed ÷ total tasks due or worked in the month.",
    type: "automatic",
    group: "automatic",
    weightage: 20,
    metric: "task_completion_rate",
    scoringMethod: "ratio",
    params: { noDataPct: 0 },
  },
  {
    key: "task_timeliness",
    name: "Task Timeliness",
    description: "Tasks completed on or before their deadline ÷ (completed + still overdue).",
    type: "automatic",
    group: "automatic",
    weightage: 15,
    metric: "task_on_time_rate",
    scoringMethod: "ratio",
    params: { noDataPct: 0 },
  },
  {
    key: "bug_management",
    name: "Bug Management",
    description: "Penalty points from confirmed bug reports (severity penalties are configurable).",
    type: "automatic",
    group: "automatic",
    weightage: 10,
    metric: "bug_penalty_points",
    scoringMethod: "deduction",
    params: { unitPct: 2, freeUnits: 0, floorPct: 0 },
  },
  {
    key: "client_changes",
    name: "Client Changes / Rework",
    description: "Client changes whose category counts against the employee (e.g. employee error).",
    type: "automatic",
    group: "automatic",
    weightage: 5,
    metric: "client_change_penalized_count",
    scoringMethod: "deduction",
    params: { unitPct: 20, freeUnits: 0, floorPct: 0 },
  },
  {
    key: "leaves",
    name: "Leaves",
    description: "HR-entered number of leaves for the month.",
    type: "automatic",
    group: "hr_metric",
    weightage: 5,
    metric: "hr_leaves",
    scoringMethod: "deduction",
    params: { unitPct: 10, freeUnits: 0, floorPct: 0 },
  },
  {
    key: "late_marks",
    name: "Late Marks",
    description: "HR-entered number of late marks for the month.",
    type: "automatic",
    group: "hr_metric",
    weightage: 5,
    metric: "hr_late_marks",
    scoringMethod: "deduction",
    params: { unitPct: 5, freeUnits: 0, floorPct: 0 },
  },
  {
    key: "discipline",
    name: "Discipline",
    description: "Workplace discipline, punctuality, following instructions, reporting discipline, general conduct.",
    type: "manual",
    group: "hr_evaluation",
    weightage: 5,
    scoringMethod: "rating",
    ratingOptions: PAR,
  },
  {
    key: "policy_compliance",
    name: "Policy Compliance",
    description: "Leave, attendance and follow-up/reporting policy; company, security and other procedures.",
    type: "manual",
    group: "hr_evaluation",
    weightage: 5,
    scoringMethod: "rating",
    ratingOptions: PAR,
  },
  {
    key: "helping_nature",
    name: "Helping Nature",
    description: "Helping colleagues, supporting the team, knowledge sharing, collaboration, assisting during urgent work.",
    type: "manual",
    group: "hr_evaluation",
    weightage: 5,
    scoringMethod: "rating",
    ratingOptions: PAR,
  },
  {
    key: "professionalism",
    name: "Professionalism",
    description: "Communication, ownership, responsibility, work attitude, meeting commitments.",
    type: "manual",
    group: "hr_evaluation",
    weightage: 5,
    scoringMethod: "rating",
    ratingOptions: PAR,
  },
  {
    key: "critical_behaviour",
    name: "Behaviour in Critical Situations",
    description: "Client escalations, urgent deadlines, critical bugs, production incidents, high-pressure and emergency work.",
    type: "manual",
    group: "hr_evaluation",
    weightage: 5,
    scoringMethod: "rating",
    ratingOptions: PAR,
  },
];

export const DEFAULT_SETTINGS = {
  bugSeverities: [
    { key: "critical", label: "Critical", penalty: 5, isActive: true },
    { key: "major", label: "Major", penalty: 3, isActive: true },
    { key: "minor", label: "Minor", penalty: 1, isActive: true },
  ],
  bugCountableStatuses: ["confirmed", "resolved"],
  clientChangeCategories: [
    { key: "requirement_change", label: "Requirement Change", countsAgainstEmployee: false },
    { key: "scope_change", label: "Scope Change", countsAgainstEmployee: false },
    { key: "client_preference", label: "Client Preference", countsAgainstEmployee: false },
    { key: "employee_error", label: "Employee Error", countsAgainstEmployee: true },
    { key: "bug_fix", label: "Bug Fix", countsAgainstEmployee: true },
    { key: "other", label: "Other", countsAgainstEmployee: false },
  ],
  uncategorizedClientChangeCounts: false,
  classifications: [
    {
      key: "needs_improvement",
      label: "Needs Improvement",
      min: 0,
      max: 35,
      tone: "danger",
      showImprovementAreas: true,
      emailMessage: "Please focus on improving these areas during the upcoming month.",
    },
    {
      key: "consistent",
      label: "Consistent Performance but Under the Acceptance Criteria",
      min: 36,
      max: 75,
      tone: "warning",
      showImprovementAreas: true,
      emailMessage:
        "Your performance has remained consistent; however, the overall score is currently below the company's defined acceptance criteria. Please continue working on the identified improvement areas.",
    },
    {
      key: "excellent",
      label: "Excellent Performance",
      min: 76,
      max: 100,
      tone: "success",
      showImprovementAreas: false,
      emailMessage: "Your performance for the month has been evaluated as excellent. Thank you for your contribution and continued professionalism.",
    },
  ],
  classificationDecimals: 0,
  improvementRule: { thresholdPct: 60, maxItems: 3 },
  appraisedRoles: ["manager", "sublead", "member", "qa"],
  automation: { autoFinalizeMode: "complete", emailsEnabled: true, maxEmailAttempts: 3 },
};
