import mongoose from "mongoose";

const attendanceSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    date: { type: String, required: true }, // "YYYY-MM-DD", org calendar day — mirrors FollowUp.date
    type: { type: String, enum: ["late", "leave"], required: true },
    note: { type: String, default: "" },
    // null for auto-generated records (see services/attendanceSweep.js) —
    // no human marked those, so there's no user to attribute them to.
    markedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    // "auto" = generated by the morning-follow-up sweep (missed submission
    // -> leave/"absent", late submission -> late); "manual" = HR/admin
    // recorded it by hand. Surfaced in the HR portal so an auto entry reads
    // as "Absent" rather than a plain "Leave".
    source: { type: String, enum: ["manual", "auto"], default: "manual" },
  },
  { timestamps: true }
);

// One entry per user/date/type — HR re-marking the same day/type upserts
// instead of creating a duplicate.
attendanceSchema.index({ user: 1, date: 1, type: 1 }, { unique: true });

export default mongoose.model("Attendance", attendanceSchema);
